version: '3'
services: 
  mongodb:
    image: mongo:6.0.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - internalnet

  node:
    image: blog-api:v2
    restart: always
    build: .
    ports: 
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongodb
    networks:
      - internalnet
    links:
      - mongodb

networks:
  internalnet:
    driver: bridge
volumes:
  mongo-data:
    driver: local